name: lint
on: [push, pull_request]

jobs:
    eslint:
        runs-on: ubuntu-latest
        steps:
            - name: check out
              uses: actions/checkout@v2

            - name: set up node
              uses: actions/setup-node@v2
              with:
                node-version: 16

            - name: install dependencies
              run: npm ci

            - name: run eslint
              run: npx eslint ./src/*.tsx

    styleline:
        runs-on: ubuntu-latest
        steps:
            - name: check out
              uses: actions/checkout@v2

            - name: set up node
              uses: actions/setup-node@v2
              with:
                node-version: 16

            - name: install dependencies
              run: npm ci

            - name: run stylelint
              run: npx stylelint "./src/**/*.css"
